In [1]:
import pandas as pd

files = ["b2b_cleaned.csv","b2b_poland_1.csv"]


clean_final_dfs = []

for f in files:
    final_df = pd.read_csv(
        f,
        encoding='latin-1',          # tolerant encoding
        encoding_errors='replace'    # prevents crash
    )
    clean_final_dfs.append(final_df)

final_final_df = pd.concat(clean_final_dfs, ignore_index=True)

final_df["Created at"] = pd.to_datetime(final_df["Created at"], errors="coerce", utc=True)
# Alleen timezone verwijderen als het echt timezone-aware is
if final_df["Created at"].dt.tz is not None:
    final_df["Created at"] = final_df["Created at"].dt.tz_localize(None)

final_df["Jaar"] = final_df["Created at"].dt.year
final_df["Maand"] = final_df["Created at"].dt.month
final_df["Dag"] = final_df["Created at"].dt.day

In [2]:
# Verwijder rijen waar Shipping Protection voorkomt
final_df = final_df[~final_df["Lineitem name"].str.contains(
    r"Patta Shipping Protection\s-\s\d+",
    regex=True,
    na=False)]

final_df

,Name,Email,Financial Status,Paid at,Fulfillment Status,Fulfilled at,Accepts Marketing,Currency,Subtotal,Shipping,...,Duties,Billing Province Name,Shipping Province Name,Payment ID,Payment Terms Name,Next Payment Due At,Payment References,Jaar,Maand,Dag
0,#273528,crooijendijk@hotmail.com,paid,2022-04-01 14:11:52 +0200,fulfilled,2022-04-04 18:05:53 +0200,yes,EUR,175.0,6.00,...,NaN,NaN,NaN,c7a3baa3f2134320672d5b4a168cf824,NaN,NaN,c7a3baa3f2134320672d5b4a168cf824,2022,4,1
1,#273527,gkrook05@gmail.com,paid,2022-04-01 14:11:46 +0200,fulfilled,2022-04-01 14:11:46 +0200,yes,EUR,200.0,0.00,...,NaN,NaN,NaN,c26425291833379.1,NaN,NaN,c26425291833379.1,2022,4,1
2,#273526,michaelrpierce95@gmail.com,paid,2022-04-01 14:10:25 +0200,fulfilled,2022-04-06 11:32:53 +0200,yes,EUR,175.0,23.86,...,NaN,Ohio,Ohio,67eee6545aa88ca5df977a47ab203050,NaN,NaN,63440bbc42ba20d691e0f2289ff16e03 + 6c45279c703...,2022,4,1
3,#273525,david_v@live.nl,paid,2022-04-01 14:09:15 +0200,fulfilled,2022-04-04 18:05:55 +0200,yes,EUR,50.0,6.00,...,NaN,NaN,NaN,fef2b166fa5efcacca8dd397e139bd69,NaN,NaN,fef2b166fa5efcacca8dd397e139bd69,2022,4,1
4,#273524,Basti.Bernsmeier@googlemail.com,refunded,2022-04-01 14:09:04 +0200,unfulfilled,NaN,no,EUR,225.0,9.41,...,NaN,NaN,NaN,5b53454ed2c718c91c700dfe6e12ba08,NaN,NaN,5b53454ed2c718c91c700dfe6e12ba08 + c2642527617...,2022,4,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18368,#260664,joppesoons@live.nl,partially_refunded,2022-01-01 01:22:02 +0100,fulfilled,2022-01-10 14:06:54 +0100,yes,EUR,307.5,6.00,...,NaN,NaN,NaN,5c78e1c76920b29660b7007f0b71ca90,NaN,NaN,5c78e1c76920b29660b7007f0b71ca90 + c2482276256...,2022,1,1
18369,#260664,joppesoons@live.nl,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022,1,1
18370,#260664,joppesoons@live.nl,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022,1,1
18371,#260664,joppesoons@live.nl,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022,1,1
18372,#260663,pancakeproduce@gmail.com,paid,2022-01-01 01:10:17 +0100,fulfilled,2022-01-05 18:38:04 +0100,yes,EUR,30.0,8.00,...,NaN,NaN,NaN,9391bd4cf2c7a20869b4c1252898a8e2,NaN,NaN,9391bd4cf2c7a20869b4c1252898a8e2,2022,1,1

In [2]:
# Save clean UTF-8 version
final_df.to_csv('wholesale_ss26.csv', index=False, encoding='utf-8')

print("Saved successfully.")

Saved successfully.

In [4]:
final_df=pd.read_csv('global.csv')
pd.set_option('display.max_columns', None)
final_df

,Name,Email,Financial Status,Paid at,Fulfillment Status,Fulfilled at,Accepts Marketing,Currency,Subtotal,Shipping,Taxes,Total,Discount Code,Discount Amount,Shipping Method,Created at,Lineitem quantity,Lineitem name,Lineitem price,Lineitem compare at price,Lineitem sku,Lineitem requires shipping,Lineitem taxable,Lineitem fulfillment status,Billing Name,Billing Street,Billing Address1,Billing Address2,Billing Company,Billing City,Billing Zip,Billing Province,Billing Country,Billing Phone,Shipping Name,Shipping Street,Shipping Address1,Shipping Address2,Shipping Company,Shipping City,Shipping Zip,Shipping Province,Shipping Country,Shipping Phone,Notes,Note Attributes,Cancelled at,Payment Method,Payment Reference,Refunded Amount,Vendor,Outstanding Balance,Employee,Location,Device ID,Id,Tags,Risk Level,Source,Lineitem discount,Tax 1 Name,Tax 1 Value,Tax 2 Name,Tax 2 Value,Tax 3 Name,Tax 3 Value,Tax 4 Name,Tax 4 Value,Tax 5 Name,Tax 5 Value,Phone,Receipt Number,Duties,Billing Province Name,Shipping Province Name,Payment ID,Payment Terms Name,Next Payment Due At,Payment References,Jaar,Maand,Dag
0,#273528,crooijendijk@hotmail.com,paid,2022-04-01 14:11:52 +0200,fulfilled,2022-04-04 18:05:53 +0200,yes,EUR,175.0,6.00,30.37,175.0,NaN,6.00,Budbee Home Delivery Evening,2022-04-01 12:11:51,1,Patta x Mizuno Sky Medal (Ivory/Red/Green) - U...,175.0,NaN,D1GD211902-US10.5,True,True,fulfilled,Chantal Rooijendijk,28 Saint Polhof,28 Saint Polhof,NaN,NaN,Ravenstein,5371 EX,NaN,NL,0648402877,Chantal Rooijendijk,28 Saint Polhof,28 Saint Polhof,NaN,NaN,Ravenstein,5371 EX,NaN,NL,0648402877,NaN,NaN,NaN,Klarna: Pay later,c26425307234339.1,0.0,Patta,0.0,NaN,NaN,NaN,4.225108e+12,NaN,Low,1520611,0.0,NL btw 21%,30.37,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,c7a3baa3f2134320672d5b4a168cf824,NaN,NaN,c7a3baa3f2134320672d5b4a168cf824,2022,4,1
1,#273527,gkrook05@gmail.com,paid,2022-04-01 14:11:46 +0200,fulfilled,2022-04-01 14:11:46 +0200,yes,EUR,200.0,0.00,34.71,200.0,NaN,0.00,NaN,2022-04-01 12:11:45,1,Patta x Alpha Industries MA-1 Amsterdam Jacket...,200.0,NaN,106117-241-L,True,True,fulfilled,Giovanni Krook,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,custom,c26425291833379.1,0.0,Patta,0.0,NaN,Patta NL - Zeedijk 68,11.0,4.225108e+12,POS - Patta NL - Zeedijk 67,Low,pos,0.0,NL btw 21%,34.71,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11-15957,NaN,NaN,NaN,c26425291833379.1,NaN,NaN,c26425291833379.1,2022,4,1
2,#273526,michaelrpierce95@gmail.com,paid,2022-04-01 14:10:25 +0200,fulfilled,2022-04-06 11:32:53 +0200,yes,EUR,175.0,23.86,0.00,175.0,NaN,23.86,UPS Express Saver,2022-04-01 12:10:24,1,Patta x Mizuno Sky Medal (Ivory/Red/Green) - U...,175.0,NaN,D1GD211902-US8.5,True,True,fulfilled,Michael Pierce,352 Wetzel Drive,352 Wetzel Drive,NaN,NaN,Chillicothe,'45601,OH,US,(740) 703-6757,Michael Pierce,352 Wetzel Drive,352 Wetzel Drive,NaN,NaN,Chillicothe,'45601,OH,US,(740) 703-6757,NaN,NaN,NaN,Klarna: Pay later + Paypal,c26425281445923.3,0.0,Patta,0.0,NaN,NaN,NaN,4.225107e+12,NaN,Low,web,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Ohio,Ohio,67eee6545aa88ca5df977a47ab203050,NaN,NaN,63440bbc42ba20d691e0f2289ff16e03 + 6c45279c703...,2022,4,1
3,#273525,david_v@live.nl,paid,2022-04-01 14:09:15 +0200,fulfilled,2022-04-04 18:05:55 +0200,yes,EUR,50.0,6.00,9.72,56.0,NaN,0.00,Budbee Home Delivery Evening,2022-04-01 12:09:14,1,byParra Thorny T-Shirt (White) - L,50.0,NaN,47305-L,True,True,fulfilled,David vermeer,250 Ringbaan Noord,250 Ringbaan Noord,NaN,NaN,Tilburg,5046 AD,NaN,NL,+31624456911,David vermeer,250 Ringbaan Noord,250 Ringbaan Noord,NaN,NaN,Tilburg,5046 AD,NaN,NL,+31624456911,NaN,NaN,NaN,iDEAL,c26425295732771.1,0.0,byParra,0.0,NaN,NaN,NaN,4.225106e+12,NaN,Low,1520611,0.0,NL btw 21%,9.72,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,fef2b166fa5efcacca8dd397e139bd69,NaN,NaN,fef2b166fa5efcacca8dd397e139bd69,2022,4,1
4,#273524,Basti.Bernsmeier@googlemail.com,refunded,2022-04-01 14:09:04 +0200,unfulfilled,NaN,no,EUR,225.0,9.41,35.92,225.0,NaN,9.41,UPS Standard,2022-04-01 12:09:03,1,byParra Thorny T-Shirt (White) - XL,50.0,NaN,47305-XL,True,True,pending,Basti Bernsmeier,Nino-Erne-Strasse 92,Nino-Erne-Strasse 92,NaN,NaN,Mainz,'55127,NaN,DE,'+49 176 64115398,Basti Bernsmeier,Nino-Erne-Strasse 92,Nino-Erne-Strasse 92,NaN,NaN,Mainz,'55127,NaN,DE,'+49 176 64115398,NaN,NaN,2022-04-11 11:53:53 +0200,Paypal,c26425276170275.1,225.0,byParra,0.0,NaN,NaN,NaN,4.225106e+12,NaN,Low,web,0.0,DE MwSt 19%,35.92,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5b53454ed2c718c91c700dfe6e12ba08,NaN,NaN,5b53454ed2c718c91c700dfe6e12ba08 + c2642527617...,2022,4,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18368,#260664,joppesoons@live.nl,partially_refunded,2022-01-01 01:22:02 +0100,fulfilled,2022-01-10 14:06:54 +0100,yes,EUR,307.5,6.00,54.41,313.5,NaN,0.00,Budbee Home Delivery Evening,2022-01-01 00:22:01,1,Patta Acid Eve T-Shirt (Water Camo) - XXL,30.0,45.0,POC-AU20-ACID-EVE-TS-003-XXL,True,True,fulfilled,Joppe Soons,"Donarstraat 5, 3",Donarstraat 5,3,NaN,Amsterdam,1076 CA,NaN,NL,06 11833791,Joppe Soons,"Donarstraat 5, 3",Donarstraat 5,3,NaN,Amsterdam,1076 CA,NaN,NL,06 11833791,NaN,locksmith: :7dde0516b6bd9831d4486a63cb9375db0e...,NaN,Paypal,c24822762569763.1,202.5,Patta,0.0,NaN,NaN,NaN,4.103256e+12,UPDATE,Low,Matrixify App,0.0,NL btw 21%,54.41,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5c78e1c76920b29660b7007f0b71ca90,NaN,NaN,5c78e1c76920b29660b7007f0b71ca90 + c2482276256...,2022,1,1
18369,#260664,joppesoons@live.nl,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022-01-01 00:22:01,1,Patta Block Coach Jacket (Old Gold/Multi) - XXL,105.0,150.0,POC-SS21-BLOCK-CJ-001-XXL,True,True,fulfilled,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Patta,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022,1,1
18370,#260664,joppesoons@live.nl,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022-01-01 00:22:01,1,Patta Original Clothing Longsleeve T-Shirt (Bl...,37.5,50.0,POC-SS21-ORIGINAL-LSTS-001-XXL,True,True,fulfilled,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Patta,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022,1,1
18371,#260664,joppesoons@live.nl,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022-01-01 00:22:01,1,Patta Heritage Reversible Jacket (Oyster Grey/...,135.0,210.0,POC-SS21-HERITAGE-REVERSIBLE-J-001-XXL,True,True,fulfilled,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Patta,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022,1,1
18372,#260663,pancakeproduce@gmail.com,paid,2022-01-01 01:10:17 +0100,fulfilled,2022-01-05 18:38:04 +0100,yes,EUR,30.0,8.00,6.60,38.0,NaN,0.00,UPS Standard,2022-01-01 00:10:16,1,Patta Arc Logo T-Shirt (Green Woodland Camo) - XL,30.0,45.0,POC-WI20-ARC-LOGO-TS-002-XL,True,True,fulfilled,Se Vranken,Lisstraat 53B,Lisstraat 53B,NaN,NaN,Rotterdam,3037 RC,NaN,NL,06 12345678,Se Vranken,Lisstraat 53B,Lisstraat 53B,NaN,NaN,Rotterdam,3037 RC,NaN,NL,06 12345678,NaN,locksmith: :7dde0516b6bd9831d4486a63cb9375db0e...,NaN,iDEAL,c24822631989283.1,0.0,Patta,0.0,NaN,NaN,NaN,4.103247e+12,NaN,Low,Matrixify App,0.0,NL btw 21%,6.60,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9391bd4cf2c7a20869b4c1252898a8e2,NaN,NaN,9391bd4cf2c7a20869b4c1252898a8e2,2022,1,1

In [ ]:
#PC6 NAAR PC4

In [4]:
import pandas as pd

# Inladen
df = pd.read_csv("global_mainline.csv")

# Zorg dat postcode string is
df["Shipping Zip"] = df["Shipping Zip"].astype(str)

# Selecteer Nederlandse records
mask_nl = df["Shipping Country"].isin(["NL", "Netherlands", "Nederland"])

# NL postcodes omzetten naar PC4
df.loc[mask_nl, "Shipping Zip"] = (
    df.loc[mask_nl, "Shipping Zip"]
        .str.replace(" ", "", regex=False)
        .str.upper()
        .str[:4]
)

# Opslaan als nieuwe CSV
df.to_csv("global_mainline_pc4.csv", index=False)

print("Nieuwe CSV aangemaakt: global_mainline_pc4.csv")

C:\Users\farza\AppData\Local\Temp\ipykernel_40328\159771761.py:4: DtypeWarning: Columns (45,62,64,66,68,76) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("global_mainline.csv")

Nieuwe CSV aangemaakt: global_mainline_pc4.csv