In [3]:
import pandas as pd

df= pd.read_csv('Patta_wholesale_26.csv')
pd.set_option('display.max_columns', None)

df

,Name,ID,Email,Status,Currency,Discount,Subtotal,Shipping,Taxes,Taxes Included,Total,Shipping Method,Custom Shipping,Total Weight,Created At,Item Quantity,Item Name,Item Price,Item Total Discount,Item Total Price,Item Sku,Item Requires Shipping,Item Taxable,Item Vendor,Item Properties,Billing Name,Billing Street,Billing Address1,Billing Address2,Billing Company,Billing City,Billing Zip,Billing Province,Billing Country,Billing Phone,Shipping Name,Shipping Street,Shipping Address1,Shipping Address2,Shipping Company,Shipping City,Shipping Zip,Shipping Province,Shipping Country,Shipping Phone,Invoice Sent At,Completed At,Order ID,Notes,Note Attributes,Tags,Tax 1 Name,Tax 1 Value,Tax 2 Name,Tax 2 Value,Tax 3 Name,Tax 3 Value,Tax 4 Name,Tax 4 Value,Tax 5 Name,Tax 5 Value,Billing Province Name,Shipping Province Name,Payment Terms Name,Next Payment Due At,PO Number
0,#D785,1.671646e+12,manish@thecreamstore.com,open,EUR,0.0,4542.5,0.0,0.0,True,4542.5,Calculated post shipping,False,0.0,2026-02-20 17:10:59 +0100,1,Patta Cassette T-Shirt (Black) - XXL,25.1,0,25.1,POC-AW26-1000-290-0156-001-XXL,True,True,Patta Original Clothing,NaN,Manish Patel,16 Water Lily Way,16 Water Lily Way,NaN,THE CREAM STORE - CONCEPTS FASHION LTD,Nuneaton,CV10 7SJ,ENG,GB,4.479506e+11,Manish Patel,"1 Charles Street, Sheffield City Centre",1 Charles Street,Sheffield City Centre,The Cream Store,Sheffield,S1 2HS,ENG,GB,4.479506e+11,NaN,NaN,NaN,NaN,NaN,Drop 2 Order,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,England,England,NaN,NaN,AW26 D2
1,#D785,NaN,manish@thecreamstore.com,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2026-02-20 17:10:59 +0100,2,Patta Square Quilted Puffer Jacket (Java) - XL,111.2,0,222.4,POC-AW26-4510-348-0069-888-XL,True,True,Patta Original Clothing,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,#D785,NaN,manish@thecreamstore.com,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2026-02-20 17:10:59 +0100,3,Patta Square Quilted Puffer Jacket (Java) - L,111.2,0,333.6,POC-AW26-4510-348-0069-888-L,True,True,Patta Original Clothing,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,#D785,NaN,manish@thecreamstore.com,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2026-02-20 17:10:59 +0100,3,Patta Square Quilted Puffer Jacket (Java) - M,111.2,0,333.6,POC-AW26-4510-348-0069-888-M,True,True,Patta Original Clothing,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,#D785,NaN,manish@thecreamstore.com,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2026-02-20 17:10:59 +0100,1,Patta Lucky 13 Varsity Knitted Cardigan (Pine ...,67.7,0,67.7,POC-AW26-7000-391-0015-387-XL,True,True,Patta Original Clothing,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5538,#D606,NaN,nikangel@bigpond.net.au,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2026-01-20 05:22:23 +0100,1,Patta Script Logo T-Shirt (White) - L,20.9,0,20.9,POC-AW26-1000-290-0163-002-L,True,True,Patta Original Clothing,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5539,#D606,NaN,nikangel@bigpond.net.au,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2026-01-20 05:22:23 +0100,1,Patta Script Logo T-Shirt (White) - M,20.9,0,20.9,POC-AW26-1000-290-0163-002-M,True,True,Patta Original Clothing,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5540,#D606,NaN,nikangel@bigpond.net.au,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2026-01-20 05:22:23 +0100,1,Patta Script Logo T-Shirt (Black) - XL,20.9,0,20.9,POC-AW26-1000-290-0163-001-XL,True,True,Patta Original Clothing,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5541,#D606,NaN,nikangel@bigpond.net.au,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2026-01-20 05:22:23 +0100,1,Patta Script Logo T-Shirt (Black) - L,20.9,0,20.9,POC-AW26-1000-290-0163-001-L,True,True,Patta Original Clothing,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5542,#D606,NaN,nikangel@bigpond.net.au,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2026-01-20 05:22:23 +0100,1,Patta Script Logo T-Shirt (Black) - M,20.9,0,20.9,POC-AW26-1000-290-0163-001-M,True,True,Patta Original Clothing,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
df["Created At"] = pd.to_datetime(df["Created At"], errors="coerce", utc=True)

# Alleen timezone verwijderen als het echt timezone-aware is
if df["Created At"].dt.tz is not None:
    df["Created At"] = df["Created At"].dt.tz_localize(None)

df["Jaar"] = df["Created At"].dt.year
df["Maand"] = df["Created At"].dt.month
df["Dag"] = df["Created At"].dt.day

print("Datum opgesplitst.")

df

Datum opgesplitst.

,Name,ID,Email,Status,Currency,Discount,Subtotal,Shipping,Taxes,Taxes Included,Total,Shipping Method,Custom Shipping,Total Weight,Created At,Item Quantity,Item Name,Item Price,Item Total Discount,Item Total Price,Item Sku,Item Requires Shipping,Item Taxable,Item Vendor,Item Properties,Billing Name,Billing Street,Billing Address1,Billing Address2,Billing Company,Billing City,Billing Zip,Billing Province,Billing Country,Billing Phone,Shipping Name,Shipping Street,Shipping Address1,Shipping Address2,Shipping Company,Shipping City,Shipping Zip,Shipping Province,Shipping Country,Shipping Phone,Invoice Sent At,Completed At,Order ID,Notes,Note Attributes,Tags,Tax 1 Name,Tax 1 Value,Tax 2 Name,Tax 2 Value,Tax 3 Name,Tax 3 Value,Tax 4 Name,Tax 4 Value,Tax 5 Name,Tax 5 Value,Billing Province Name,Shipping Province Name,Payment Terms Name,Next Payment Due At,PO Number,Jaar,Maand,Dag
0,#D785,1.671646e+12,manish@thecreamstore.com,open,EUR,0.0,4542.5,0.0,0.0,True,4542.5,Calculated post shipping,False,0.0,2026-02-20 16:10:59,1,Patta Cassette T-Shirt (Black) - XXL,25.1,0,25.1,POC-AW26-1000-290-0156-001-XXL,True,True,Patta Original Clothing,NaN,Manish Patel,16 Water Lily Way,16 Water Lily Way,NaN,THE CREAM STORE - CONCEPTS FASHION LTD,Nuneaton,CV10 7SJ,ENG,GB,4.479506e+11,Manish Patel,"1 Charles Street, Sheffield City Centre",1 Charles Street,Sheffield City Centre,The Cream Store,Sheffield,S1 2HS,ENG,GB,4.479506e+11,NaN,NaN,NaN,NaN,NaN,Drop 2 Order,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,England,England,NaN,NaN,AW26 D2,2026,2,20
1,#D785,NaN,manish@thecreamstore.com,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2026-02-20 16:10:59,2,Patta Square Quilted Puffer Jacket (Java) - XL,111.2,0,222.4,POC-AW26-4510-348-0069-888-XL,True,True,Patta Original Clothing,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2026,2,20
2,#D785,NaN,manish@thecreamstore.com,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2026-02-20 16:10:59,3,Patta Square Quilted Puffer Jacket (Java) - L,111.2,0,333.6,POC-AW26-4510-348-0069-888-L,True,True,Patta Original Clothing,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2026,2,20
3,#D785,NaN,manish@thecreamstore.com,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2026-02-20 16:10:59,3,Patta Square Quilted Puffer Jacket (Java) - M,111.2,0,333.6,POC-AW26-4510-348-0069-888-M,True,True,Patta Original Clothing,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2026,2,20
4,#D785,NaN,manish@thecreamstore.com,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2026-02-20 16:10:59,1,Patta Lucky 13 Varsity Knitted Cardigan (Pine ...,67.7,0,67.7,POC-AW26-7000-391-0015-387-XL,True,True,Patta Original Clothing,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2026,2,20
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5538,#D606,NaN,nikangel@bigpond.net.au,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2026-01-20 04:22:23,1,Patta Script Logo T-Shirt (White) - L,20.9,0,20.9,POC-AW26-1000-290-0163-002-L,True,True,Patta Original Clothing,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2026,1,20
5539,#D606,NaN,nikangel@bigpond.net.au,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2026-01-20 04:22:23,1,Patta Script Logo T-Shirt (White) - M,20.9,0,20.9,POC-AW26-1000-290-0163-002-M,True,True,Patta Original Clothing,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2026,1,20
5540,#D606,NaN,nikangel@bigpond.net.au,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2026-01-20 04:22:23,1,Patta Script Logo T-Shirt (Black) - XL,20.9,0,20.9,POC-AW26-1000-290-0163-001-XL,True,True,Patta Original Clothing,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2026,1,20
5541,#D606,NaN,nikangel@bigpond.net.au,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2026-01-20 04:22:23,1,Patta Script Logo T-Shirt (Black) - L,20.9,0,20.9,POC-AW26-1000-290-0163-001-L,True,True,Patta Original Clothing,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2026,1,20
5542,#D606,NaN,nikangel@bigpond.net.au,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2026-01-20 04:22:23,1,Patta Script Logo T-Shirt (Black) - M,20.9,0,20.9,POC-AW26-1000-290-0163-001-M,True,True,Patta Original Clothing,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2026,1,20

In [10]:
df.to_csv("b2b_cleaned.csv", index=False)

print("Bestand opgeslagen.")

Bestand opgeslagen.

In [8]:
# # Verwijder rijen waar Shipping Protection voorkomt
# df = df[~df["Lineitem name"].str.contains(
#     r"Patta Shipping Protection\s-\s\d+",
#     regex=True,
#     na=False
# )]

# #df.to_csv("nieuwe_naam.csv", index=False)

# print("Shipping Protection rijen verwijderd.")
# df

In [6]:
#Om alleen mainline items over te houden

df["Lineitem sku"] = df["Lineitem sku"].astype(str).str.strip()

df = df[df["Lineitem sku"].str.startswith("POC-", na=False)]

print("Aantal POC-items:", len(df))

if len(df) > 0:
    df.to_csv("global_mainline.csv", index=False)
    print("Bestand opgeslagen met alleen POC-items.")
else:
    print("Geen POC-items gevonden.")

Aantal POC-items: 171254
Bestand opgeslagen met alleen POC-items.