In [1]:
import pandas as pd

df= pd.read_csv('wholesale.csv')
pd.set_option('display.max_columns', None)

df

C:\Users\farza\AppData\Local\Temp\ipykernel_40628\2416039113.py:3: DtypeWarning: Columns (3,44,45,46,47,48,53,75,78) have mixed types. Specify dtype option on import or set low_memory=False.
  df= pd.read_csv('wholesale.csv')

,Name,Email,Financial Status,Paid at,Fulfillment Status,Fulfilled at,Accepts Marketing,Currency,Subtotal,Shipping,Taxes,Total,Discount Code,Discount Amount,Shipping Method,Created at,Lineitem quantity,Lineitem name,Lineitem price,Lineitem compare at price,Lineitem sku,Lineitem requires shipping,Lineitem taxable,Lineitem fulfillment status,Billing Name,Billing Street,Billing Address1,Billing Address2,Billing Company,Billing City,Billing Zip,Billing Province,Billing Country,Billing Phone,Shipping Name,Shipping Street,Shipping Address1,Shipping Address2,Shipping Company,Shipping City,Shipping Zip,Shipping Province,Shipping Country,Shipping Phone,Notes,Note Attributes,Cancelled at,Payment Method,Payment Reference,Refunded Amount,Vendor,Outstanding Balance,Employee,Location,Device ID,Id,Tags,Risk Level,Source,Lineitem discount,Tax 1 Name,Tax 1 Value,Tax 2 Name,Tax 2 Value,Tax 3 Name,Tax 3 Value,Tax 4 Name,Tax 4 Value,Tax 5 Name,Tax 5 Value,Phone,Receipt Number,Duties,Billing Province Name,Shipping Province Name,Payment ID,Payment Terms Name,Next Payment Due At,Payment References
0,#WS1922,hschoi@worksout.co.kr,pending,NaN,unfulfilled,NaN,yes,EUR,13813.1,0.0,0.0,13813.1,NaN,0.0,Calculated post shipping,2026-03-02 22:57:52 +0100,1,Patta Leather Hooded Bomber Jacket (Moonless N...,199.6,NaN,POC-AW26-6150-348-0070-086-XL,True,True,pending,NaN,"24, World Cup buk-ro 23-gil, Mapo-gu","24, World Cup buk-ro 23-gil, Mapo-gu",NaN,WORKSOUT Inc.,Seoul,'03966,KR-11,KR,8.210649e+11,NaN,"1-40, Bukhangbaehu-ro, Seo-gu","1-40, Bukhangbaehu-ro, Seo-gu",NaN,WORKSOUT Inc. / WAREHOUSE,Incheon,'22767,KR-28,KR,8.210649e+11,NaN,NaN,NaN,manual,NaN,0.0,Patta Original Clothing,13813.1,Jeffrey Verwey,NaN,NaN,1.301031e+13,"b2b, Drop 1 Order, Not Synced, SendToSAP",Low,1758145,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Seoul,Incheon,rc3HFc6I621IVm8q654Tc6veU,Net 15,2026-02-12 16:11:57 +0100,rc3HFc6I621IVm8q654Tc6veU
1,#WS1922,hschoi@worksout.co.kr,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2026-03-02 22:57:52 +0100,1,Patta Leather Hooded Bomber Jacket (Moonless N...,199.6,NaN,POC-AW26-6150-348-0070-086-L,True,True,pending,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Patta Original Clothing,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,#WS1922,hschoi@worksout.co.kr,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2026-03-02 22:57:52 +0100,1,Patta Leather Hooded Bomber Jacket (Moonless N...,199.6,NaN,POC-AW26-6150-348-0070-086-M,True,True,pending,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Patta Original Clothing,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,#WS1922,hschoi@worksout.co.kr,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2026-03-02 22:57:52 +0100,1,Patta Leather Hooded Bomber Jacket (Moonless N...,199.6,NaN,POC-AW26-6150-348-0070-086-S,True,True,pending,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Patta Original Clothing,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,#WS1922,hschoi@worksout.co.kr,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2026-03-02 22:57:52 +0100,1,Patta Corduroy Bomber Jacket (Climbing Ivy) - XL,99.7,NaN,POC-AW26-3900-348-0052-183-XL,True,True,pending,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Patta Original Clothing,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45802,#WS1013,alex.bruzzi@undefeated.com,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024-06-18 12:04:52 +0200,6,Patta Snake Heart T-Shirt - Moonless Night - L,24.0,0.0,POC-SS25-1000-290-0063-086-L,True,True,pending,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,SNL100773,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
45803,#WS1013,alex.bruzzi@undefeated.com,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024-06-18 12:04:52 +0200,10,Patta Snake Heart T-Shirt - Moonless Night - M,24.0,0.0,POC-SS25-1000-290-0063-086-M,True,True,pending,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,SNL100773,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
45804,#WS1013,alex.bruzzi@undefeated.com,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024-06-18 12:04:52 +0200,3,Patta Snake Heart T-Shirt - Moonless Night - XXL,24.0,0.0,POC-SS25-1000-290-0063-086-XXL,True,True,pending,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,SNL100773,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
45805,#WS1013,alex.bruzzi@undefeated.com,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024-06-18 12:04:52 +0200,6,Patta Old School Knitted Sweater - Moonless Ni...,66.0,0.0,POC-SS25-7000-324-0006-086-XL,True,True,pending,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,SNL100504,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
45806,#WS1013,alex.bruzzi@undefeated.com,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024-06-18 12:04:52 +0200,18,Patta Frayed Woodland Camo Sports Cap (Sand Do...,26.0,0.0,POC-SS25-4100-815-0007-193,True,True,pending,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,SNL100760,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
df["Created at"] = pd.to_datetime(df["Created at"], errors="coerce", utc=True)

# Alleen timezone verwijderen als het echt timezone-aware is
if df["Created at"].dt.tz is not None:
    df["Created at"] = df["Created at"].dt.tz_localize(None)

df["Jaar"] = df["Created at"].dt.year
df["Maand"] = df["Created at"].dt.month
df["Dag"] = df["Created at"].dt.day

print("Datum opgesplitst.")

df

Datum opgesplitst.

,Name,Email,Financial Status,Paid at,Fulfillment Status,Fulfilled at,Accepts Marketing,Currency,Subtotal,Shipping,Taxes,Total,Discount Code,Discount Amount,Shipping Method,Created at,Lineitem quantity,Lineitem name,Lineitem price,Lineitem compare at price,Lineitem sku,Lineitem requires shipping,Lineitem taxable,Lineitem fulfillment status,Billing Name,Billing Street,Billing Address1,Billing Address2,Billing Company,Billing City,Billing Zip,Billing Province,Billing Country,Billing Phone,Shipping Name,Shipping Street,Shipping Address1,Shipping Address2,Shipping Company,Shipping City,Shipping Zip,Shipping Province,Shipping Country,Shipping Phone,Notes,Note Attributes,Cancelled at,Payment Method,Payment Reference,Refunded Amount,Vendor,Outstanding Balance,Employee,Location,Device ID,Id,Tags,Risk Level,Source,Lineitem discount,Tax 1 Name,Tax 1 Value,Tax 2 Name,Tax 2 Value,Tax 3 Name,Tax 3 Value,Tax 4 Name,Tax 4 Value,Tax 5 Name,Tax 5 Value,Phone,Receipt Number,Duties,Billing Province Name,Shipping Province Name,Payment ID,Payment Terms Name,Next Payment Due At,Payment References,Jaar,Maand,Dag
0,#WS1922,hschoi@worksout.co.kr,pending,NaN,unfulfilled,NaN,yes,EUR,13813.1,0.0,0.0,13813.1,NaN,0.0,Calculated post shipping,2026-03-02 21:57:52,1,Patta Leather Hooded Bomber Jacket (Moonless N...,199.6,NaN,POC-AW26-6150-348-0070-086-XL,True,True,pending,NaN,"24, World Cup buk-ro 23-gil, Mapo-gu","24, World Cup buk-ro 23-gil, Mapo-gu",NaN,WORKSOUT Inc.,Seoul,'03966,KR-11,KR,8.210649e+11,NaN,"1-40, Bukhangbaehu-ro, Seo-gu","1-40, Bukhangbaehu-ro, Seo-gu",NaN,WORKSOUT Inc. / WAREHOUSE,Incheon,'22767,KR-28,KR,8.210649e+11,NaN,NaN,NaN,manual,NaN,0.0,Patta Original Clothing,13813.1,Jeffrey Verwey,NaN,NaN,1.301031e+13,"b2b, Drop 1 Order, Not Synced, SendToSAP",Low,1758145,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Seoul,Incheon,rc3HFc6I621IVm8q654Tc6veU,Net 15,2026-02-12 16:11:57 +0100,rc3HFc6I621IVm8q654Tc6veU,2026,3,2
1,#WS1922,hschoi@worksout.co.kr,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2026-03-02 21:57:52,1,Patta Leather Hooded Bomber Jacket (Moonless N...,199.6,NaN,POC-AW26-6150-348-0070-086-L,True,True,pending,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Patta Original Clothing,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2026,3,2
2,#WS1922,hschoi@worksout.co.kr,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2026-03-02 21:57:52,1,Patta Leather Hooded Bomber Jacket (Moonless N...,199.6,NaN,POC-AW26-6150-348-0070-086-M,True,True,pending,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Patta Original Clothing,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2026,3,2
3,#WS1922,hschoi@worksout.co.kr,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2026-03-02 21:57:52,1,Patta Leather Hooded Bomber Jacket (Moonless N...,199.6,NaN,POC-AW26-6150-348-0070-086-S,True,True,pending,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Patta Original Clothing,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2026,3,2
4,#WS1922,hschoi@worksout.co.kr,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2026-03-02 21:57:52,1,Patta Corduroy Bomber Jacket (Climbing Ivy) - XL,99.7,NaN,POC-AW26-3900-348-0052-183-XL,True,True,pending,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Patta Original Clothing,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2026,3,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45802,#WS1013,alex.bruzzi@undefeated.com,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024-06-18 10:04:52,6,Patta Snake Heart T-Shirt - Moonless Night - L,24.0,0.0,POC-SS25-1000-290-0063-086-L,True,True,pending,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,SNL100773,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024,6,18
45803,#WS1013,alex.bruzzi@undefeated.com,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024-06-18 10:04:52,10,Patta Snake Heart T-Shirt - Moonless Night - M,24.0,0.0,POC-SS25-1000-290-0063-086-M,True,True,pending,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,SNL100773,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024,6,18
45804,#WS1013,alex.bruzzi@undefeated.com,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024-06-18 10:04:52,3,Patta Snake Heart T-Shirt - Moonless Night - XXL,24.0,0.0,POC-SS25-1000-290-0063-086-XXL,True,True,pending,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,SNL100773,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024,6,18
45805,#WS1013,alex.bruzzi@undefeated.com,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024-06-18 10:04:52,6,Patta Old School Knitted Sweater - Moonless Ni...,66.0,0.0,POC-SS25-7000-324-0006-086-XL,True,True,pending,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,SNL100504,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024,6,18
45806,#WS1013,alex.bruzzi@undefeated.com,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024-06-18 10:04:52,18,Patta Frayed Woodland Camo Sports Cap (Sand Do...,26.0,0.0,POC-SS25-4100-815-0007-193,True,True,pending,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,SNL100760,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024,6,18

In [4]:
df = df[~df["Email"].str.contains(r"@patta\.nl", case=False, na=False)]

df

,Name,Email,Financial Status,Paid at,Fulfillment Status,Fulfilled at,Accepts Marketing,Currency,Subtotal,Shipping,Taxes,Total,Discount Code,Discount Amount,Shipping Method,Created at,Lineitem quantity,Lineitem name,Lineitem price,Lineitem compare at price,Lineitem sku,Lineitem requires shipping,Lineitem taxable,Lineitem fulfillment status,Billing Name,Billing Street,Billing Address1,Billing Address2,Billing Company,Billing City,Billing Zip,Billing Province,Billing Country,Billing Phone,Shipping Name,Shipping Street,Shipping Address1,Shipping Address2,Shipping Company,Shipping City,Shipping Zip,Shipping Province,Shipping Country,Shipping Phone,Notes,Note Attributes,Cancelled at,Payment Method,Payment Reference,Refunded Amount,Vendor,Outstanding Balance,Employee,Location,Device ID,Id,Tags,Risk Level,Source,Lineitem discount,Tax 1 Name,Tax 1 Value,Tax 2 Name,Tax 2 Value,Tax 3 Name,Tax 3 Value,Tax 4 Name,Tax 4 Value,Tax 5 Name,Tax 5 Value,Phone,Receipt Number,Duties,Billing Province Name,Shipping Province Name,Payment ID,Payment Terms Name,Next Payment Due At,Payment References,Jaar,Maand,Dag
0,#WS1922,hschoi@worksout.co.kr,pending,NaN,unfulfilled,NaN,yes,EUR,13813.1,0.0,0.0,13813.1,NaN,0.0,Calculated post shipping,2026-03-02 21:57:52,1,Patta Leather Hooded Bomber Jacket (Moonless N...,199.6,NaN,POC-AW26-6150-348-0070-086-XL,True,True,pending,NaN,"24, World Cup buk-ro 23-gil, Mapo-gu","24, World Cup buk-ro 23-gil, Mapo-gu",NaN,WORKSOUT Inc.,Seoul,'03966,KR-11,KR,8.210649e+11,NaN,"1-40, Bukhangbaehu-ro, Seo-gu","1-40, Bukhangbaehu-ro, Seo-gu",NaN,WORKSOUT Inc. / WAREHOUSE,Incheon,'22767,KR-28,KR,8.210649e+11,NaN,NaN,NaN,manual,NaN,0.0,Patta Original Clothing,13813.1,Jeffrey Verwey,NaN,NaN,1.301031e+13,"b2b, Drop 1 Order, Not Synced, SendToSAP",Low,1758145,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Seoul,Incheon,rc3HFc6I621IVm8q654Tc6veU,Net 15,2026-02-12 16:11:57 +0100,rc3HFc6I621IVm8q654Tc6veU,2026,3,2
1,#WS1922,hschoi@worksout.co.kr,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2026-03-02 21:57:52,1,Patta Leather Hooded Bomber Jacket (Moonless N...,199.6,NaN,POC-AW26-6150-348-0070-086-L,True,True,pending,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Patta Original Clothing,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2026,3,2
2,#WS1922,hschoi@worksout.co.kr,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2026-03-02 21:57:52,1,Patta Leather Hooded Bomber Jacket (Moonless N...,199.6,NaN,POC-AW26-6150-348-0070-086-M,True,True,pending,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Patta Original Clothing,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2026,3,2
3,#WS1922,hschoi@worksout.co.kr,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2026-03-02 21:57:52,1,Patta Leather Hooded Bomber Jacket (Moonless N...,199.6,NaN,POC-AW26-6150-348-0070-086-S,True,True,pending,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Patta Original Clothing,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2026,3,2
4,#WS1922,hschoi@worksout.co.kr,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2026-03-02 21:57:52,1,Patta Corduroy Bomber Jacket (Climbing Ivy) - XL,99.7,NaN,POC-AW26-3900-348-0052-183-XL,True,True,pending,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Patta Original Clothing,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2026,3,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45802,#WS1013,alex.bruzzi@undefeated.com,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024-06-18 10:04:52,6,Patta Snake Heart T-Shirt - Moonless Night - L,24.0,0.0,POC-SS25-1000-290-0063-086-L,True,True,pending,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,SNL100773,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024,6,18
45803,#WS1013,alex.bruzzi@undefeated.com,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024-06-18 10:04:52,10,Patta Snake Heart T-Shirt - Moonless Night - M,24.0,0.0,POC-SS25-1000-290-0063-086-M,True,True,pending,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,SNL100773,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024,6,18
45804,#WS1013,alex.bruzzi@undefeated.com,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024-06-18 10:04:52,3,Patta Snake Heart T-Shirt - Moonless Night - XXL,24.0,0.0,POC-SS25-1000-290-0063-086-XXL,True,True,pending,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,SNL100773,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024,6,18
45805,#WS1013,alex.bruzzi@undefeated.com,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024-06-18 10:04:52,6,Patta Old School Knitted Sweater - Moonless Ni...,66.0,0.0,POC-SS25-7000-324-0006-086-XL,True,True,pending,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,SNL100504,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024,6,18
45806,#WS1013,alex.bruzzi@undefeated.com,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024-06-18 10:04:52,18,Patta Frayed Woodland Camo Sports Cap (Sand Do...,26.0,0.0,POC-SS25-4100-815-0007-193,True,True,pending,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,SNL100760,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024,6,18

In [5]:
df.to_csv("wholesale_cleaned.csv", index=False)

print("Bestand opgeslagen.")

Bestand opgeslagen.

In [ ]:
# # Verwijder rijen waar Shipping Protection voorkomt
# df = df[~df["Lineitem name"].str.contains(
#     r"Patta Shipping Protection\s-\s\d+",
#     regex=True,
#     na=False
# )]

# #df.to_csv("nieuwe_naam.csv", index=False)

# print("Shipping Protection rijen verwijderd.")
# df

In [6]:
#Om alleen mainline items over te houden

df["Lineitem sku"] = df["Lineitem sku"].astype(str).str.strip()

df = df[df["Lineitem sku"].str.startswith("POC-", na=False)]

print("Aantal POC-items:", len(df))

if len(df) > 0:
    df.to_csv("global_mainline.csv", index=False)
    print("Bestand opgeslagen met alleen POC-items.")
else:
    print("Geen POC-items gevonden.")

Aantal POC-items: 171254
Bestand opgeslagen met alleen POC-items.