In [36]:
import pandas as pd

df= pd.read_csv('us.csv')
pd.set_option('display.max_columns', None)

df

,Name,Email,Financial Status,Paid at,Fulfillment Status,Fulfilled at,Accepts Marketing,Currency,Subtotal,Shipping,Taxes,Total,Discount Code,Discount Amount,Shipping Method,Created at,Lineitem quantity,Lineitem name,Lineitem price,Lineitem compare at price,Lineitem sku,Lineitem requires shipping,Lineitem taxable,Lineitem fulfillment status,Billing Name,Billing Street,Billing Address1,Billing Address2,Billing Company,Billing City,Billing Zip,Billing Province,Billing Country,Billing Phone,Shipping Name,Shipping Street,Shipping Address1,Shipping Address2,Shipping Company,Shipping City,Shipping Zip,Shipping Province,Shipping Country,Shipping Phone,Notes,Note Attributes,Cancelled at,Payment Method,Payment Reference,Refunded Amount,Vendor,Outstanding Balance,Employee,Location,Device ID,Id,Tags,Risk Level,Source,Lineitem discount,Tax 1 Name,Tax 1 Value,Tax 2 Name,Tax 2 Value,Tax 3 Name,Tax 3 Value,Tax 4 Name,Tax 4 Value,Tax 5 Name,Tax 5 Value,Phone,Receipt Number,Duties,Billing Province Name,Shipping Province Name,Payment ID,Payment Terms Name,Next Payment Due At,Payment References
0,US4419,robelm11@gmail.com,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12/31/2025 7:13,1,Patta Embroidered Fire Panther Hooded Sweater ...,152.0,NaN,POC-AW25-2050-325-0026-001-L,True,True,fulfilled,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Patta,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,US4414,nzkatapo@gmail.com,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12/25/2025 22:00,1,Patta Quilted Script Logo Puffer Jacket (Navy)...,324.0,NaN,POC-AW25-3200-348-0031-202-L,True,True,fulfilled,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Patta,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,US4412,agretana69@icloud.com,paid,12/25/2025 0:21,fulfilled,1/8/2026 15:51,yes,USD,66.0,16.8,0.0,82.8,NaN,0.0,UPS Express Saver,12/24/2025 20:20,1,Patta Lighters T-Shirt (Parisian Night ) - XL,64.0,NaN,POC-AW25-1000-290-0095-202-XL,True,True,fulfilled,Andres Retana,9001 Shellwood Ct,9001 Shellwood Ct,NaN,NaN,Raleigh,27617,NC,US,NaN,Andres Retana,9001 Shellwood Ct,9001 Shellwood Ct,NaN,NaN,Raleigh,27617,NC,US,9199876709,NaN,delivery_defense_score: 891,NaN,Adyen Payments - Credit Cards,rfETfyiWUaXtr6wbW1or3e12i,0.0,Patta,0.0,NaN,NaN,NaN,1.651530e+13,"DeliveryDefense risk level: Low, SupplierChina...",Low,web,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,North Carolina,North Carolina,rfETfyiWUaXtr6wbW1or3e12i,NaN,NaN,rfETfyiWUaXtr6wbW1or3e12i + aSF3q6fhQlGwkgGOOy...
3,US4411,corey.lepore@gmail.com,paid,12/24/2025 1:39,fulfilled,1/4/2026 5:45,yes,USD,75.0,21.0,0.0,96.0,NaN,0.0,UPS Express,12/23/2025 21:38,1,Patta Oversized Tote Bag (Black),75.0,NaN,POC-AW25-3500-380-0001-001,True,True,fulfilled,Corey Lepore,2 Lyons Rd,2 Lyons Rd,NaN,NaN,Armonk,10504,NY,US,NaN,Corey Lepore,2 Lyons Road,2 Lyons Road,NaN,NaN,Armonk,10504,NY,US,9144190346,NaN,delivery_defense_score: 880,NaN,Adyen Payments - Credit Cards,rBsHHagYQ9qkJ9Ta5tB4FIkqY,0.0,Patta,0.0,NaN,NaN,NaN,1.651410e+13,"DeliveryDefense risk level: Low, SupplierChina...",Low,web,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,New York,New York,rBsHHagYQ9qkJ9Ta5tB4FIkqY,NaN,NaN,rBsHHagYQ9qkJ9Ta5tB4FIkqY + aCcnyMDun4rw99nuLy...
4,US4410,hemicuda620@gmail.com,paid,12/23/2025 17:03,fulfilled,1/5/2026 14:45,yes,USD,152.0,16.8,0.0,168.8,NaN,0.0,UPS Express Saver,12/23/2025 13:01,1,Patta Embroidered Fire Panther Hooded Sweater ...,152.0,NaN,POC-AW25-2050-325-0026-001-L,True,True,fulfilled,Aspen Goodman,"576 Jaques Avenue, 2",576 Jaques Avenue,2,NaN,Rahway,7065,NJ,US,7324231758,Aspen Goodman,"576 Jaques Avenue, 2",576 Jaques Avenue,2,NaN,Rahway,7065,NJ,US,7324231758,NaN,delivery_defense_score: 866,NaN,Adyen Payments - Credit Cards,r7uOzcrG6pVrS9zGVejo25uNn,0.0,Patta,0.0,NaN,NaN,NaN,1.651350e+13,"DeliveryDefense risk level: Low, SupplierChina...",Low,web,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,New Jersey,New Jersey,r7uOzcrG6pVrS9zGVejo25uNn,NaN,NaN,r7uOzcrG6pVrS9zGVejo25uNn + at7dqUCKyuJDiSZK9a...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3549,US1007,hana.salem@hotmail.fr,paid,10/4/2023 11:56,unfulfilled,NaN,no,USD,45.0,0.0,0.0,45.0,NaN,0.0,NaN,10/4/2023 11:56,1,Patta Apple T-Shirt (Odyssey Gray) - M,45.0,NaN,POC-SS23-APPLE-TS-002-M,True,True,pending,Dont ship ME,1600 Amphitheatre Pkwy,1600 Amphitheatre Pkwy,NaN,Pattta,Mountain View,94043,CA,US,NaN,Dont ship ME,1600 Amphitheatre Pkwy,1600 Amphitheatre Pkwy,NaN,Pattta,Mountain View,94043,CA,US,NaN,NaN,NaN,NaN,manual,r8NVWFtC5aAgKKDDUC45iyaCh,0.0,Patta,0.0,Hana Salem,NaN,NaN,5.514810e+12,NaN,Low,shopify_draft_order,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,California,California,r8NVWFtC5aAgKKDDUC45iyaCh,NaN,NaN,r8NVWFtC5aAgKKDDUC45iyaCh
3550,US1006,leander@patta.nl,paid,9/28/2023 9:47,fulfilled,9/28/2023 9:49,no,USD,45.0,0.0,0.0,45.0,NaN,0.0,NaN,9/28/2023 9:47,1,Patta Apple T-Shirt (Black) - XS,45.0,NaN,POC-SS23-APPLE-TS-001-XS,True,True,fulfilled,Christopher Guzman TEST,504 E 79th St apt 2c,504 E 79th St apt 2c,NaN,NaN,New York,10075,NY,US,NaN,Christopher Guzman TEST,"317 Dundas St W, Toronto, ON M5T 1G4, Canada","317 Dundas St W, Toronto, ON M5T 1G4, Canada",NaN,NaN,toronto,M5T 1G4,ON,CA,NaN,"2023-09-29 15:50 UTC\nReturnGO, RMA2156701:\nR...",NaN,NaN,manual,r0YurWeCgffOT8z8VPZn5rBRz,0.0,Patta,0.0,Hana Salem,NaN,NaN,5.508500e+12,Return requested via ReturnGO,Low,shopify_draft_order,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,New York,Ontario,r0YurWeCgffOT8z8VPZn5rBRz,NaN,NaN,r0YurWeCgffOT8z8VPZn5rBRz
3551,US1005,tomas@patta.nl,paid,9/28/2023 9:43,fulfilled,9/28/2023 9:49,no,USD,45.0,0.0,7.5,45.0,NaN,0.0,NaN,9/28/2023 9:43,1,Patta Apple T-Shirt (Black) - S,45.0,NaN,POC-SS23-APPLE-TS-001-S,True,True,fulfilled,TEST ACCOUNT DONT SHIP,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,TEST ACCOUNT DONT SHIP TEST ACCOUNT DONT SHIP,"1600 Pennsylvania Avenue NW, Washington, DC 20...","1600 Pennsylvania Avenue NW, Washington, DC 20...",NaN,Patta,DC,20500,DC,US,NaN,"2023-09-29 15:02 UTC\nReturnGO, RMA2156433:\nR...",NaN,NaN,manual,rZrdQkDb5uw7p7ohMxUa79w6K,0.0,Patta,0.0,Hana Salem,Patta UK - Bleckmann Warehouse,NaN,5.508500e+12,Return requested via ReturnGO,Low,shopify_draft_order,0,GB VAT 20%,7.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Washington DC,rZrdQkDb5uw7p7ohMxUa79w6K,NaN,NaN,rZrdQkDb5uw7p7ohMxUa79w6K
3552,US1003,leander@patta.nl,paid,8/21/2023 6:12,fulfilled,9/1/2023 10:43,no,USD,194.0,23.5,0.0,217.5,NaN,0.0,UPS Express,8/21/2023 6:12,1,Patta Apple T-Shirt (Odyssey Gray) - M,45.0,NaN,POC-SS23-APPLE-TS-002-M,True,True,fulfilled,Christopher Guzman TEST,504 E 79th St apt 2c,504 E 79th St apt 2c,NaN,NaN,New York,10075,NY,US,NaN,Christopher Guzman TEST,504 E 79th St apt 2c,504 E 79th St apt 2c,NaN,NaN,New York,10075,NY,US,NaN,NaN,NaN,NaN,manual,rC5TYcZQZGrmqlF0ywIiUOrsY,0.0,Patta,0.0,NaN,NaN,NaN,5.442750e+12,NaN,Low,shopify_draft_order,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,New York,New York,rC5TYcZQZGrmqlF0ywIiUOrsY,NaN,NaN,rC5TYcZQZGrmqlF0ywIiUOrsY
3553,US1003,leander@patta.nl,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8/21/2023 6:12,1,Patta Argyle Knitted Cardigan (Light Brown Mel...,149.0,NaN,POC-SS23-ARGYLE-KC-001-L,True,True,fulfilled,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Patta,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [41]:
df["Created at"] = pd.to_datetime(df["Created at"], errors="coerce", utc=True)

# Alleen timezone verwijderen als het echt timezone-aware is
if df["Created at"].dt.tz is not None:
    df["Created at"] = df["Created at"].dt.tz_localize(None)

df["Jaar"] = df["Created at"].dt.year
df["Maand"] = df["Created at"].dt.month
df["Dag"] = df["Created at"].dt.day

In [42]:
# df["Lineitem sku"] = (
#     df["Lineitem sku"]
#     .astype(str)
#     .str.strip()          
# )

# df = df[df["Lineitem sku"].str.contains(
#     r"^POC-[A-Z0-9-]+$",
#     regex=True,
#     case=False,           # hoofdletterongevoelig
#     na=False
# )]
df["Lineitem sku"] = df["Lineitem sku"].astype(str).str.strip()

df = df[df["Lineitem sku"].str.startswith("POC-", na=False)]

print("Aantal POC-items:", len(df))

if len(df) > 0:
    df.to_csv("US_mainline.csv", index=False)
    print("Bestand opgeslagen met alleen POC-items.")
else:
    print("Geen POC-items gevonden.")

Aantal POC-items: 1749
Bestand opgeslagen met alleen POC-items.

In [43]:
df=pd.read_csv('US_mainline.csv')
df

,Name,Email,Financial Status,Paid at,Fulfillment Status,Fulfilled at,Accepts Marketing,Currency,Subtotal,Shipping,Taxes,Total,Discount Code,Discount Amount,Shipping Method,Created at,Lineitem quantity,Lineitem name,Lineitem price,Lineitem compare at price,Lineitem sku,Lineitem requires shipping,Lineitem taxable,Lineitem fulfillment status,Billing Name,Billing Street,Billing Address1,Billing Address2,Billing Company,Billing City,Billing Zip,Billing Province,Billing Country,Billing Phone,Shipping Name,Shipping Street,Shipping Address1,Shipping Address2,Shipping Company,Shipping City,Shipping Zip,Shipping Province,Shipping Country,Shipping Phone,Notes,Note Attributes,Cancelled at,Payment Method,Payment Reference,Refunded Amount,Vendor,Outstanding Balance,Employee,Location,Device ID,Id,Tags,Risk Level,Source,Lineitem discount,Tax 1 Name,Tax 1 Value,Tax 2 Name,Tax 2 Value,Tax 3 Name,Tax 3 Value,Tax 4 Name,Tax 4 Value,Tax 5 Name,Tax 5 Value,Phone,Receipt Number,Duties,Billing Province Name,Shipping Province Name,Payment ID,Payment Terms Name,Next Payment Due At,Payment References,Jaar,Maand,Dag
0,US4419,robelm11@gmail.com,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2025-12-31 07:13:00,1,Patta Embroidered Fire Panther Hooded Sweater ...,152.0,NaN,POC-AW25-2050-325-0026-001-L,True,True,fulfilled,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Patta,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2025,12,31
1,US4414,nzkatapo@gmail.com,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2025-12-25 22:00:00,1,Patta Quilted Script Logo Puffer Jacket (Navy)...,324.0,NaN,POC-AW25-3200-348-0031-202-L,True,True,fulfilled,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Patta,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2025,12,25
2,US4412,agretana69@icloud.com,paid,12/25/2025 0:21,fulfilled,1/8/2026 15:51,yes,USD,66.0,16.8,0.0,82.8,NaN,0.0,UPS Express Saver,2025-12-24 20:20:00,1,Patta Lighters T-Shirt (Parisian Night ) - XL,64.0,NaN,POC-AW25-1000-290-0095-202-XL,True,True,fulfilled,Andres Retana,9001 Shellwood Ct,9001 Shellwood Ct,NaN,NaN,Raleigh,27617,NC,US,NaN,Andres Retana,9001 Shellwood Ct,9001 Shellwood Ct,NaN,NaN,Raleigh,27617,NC,US,9199876709,NaN,delivery_defense_score: 891,NaN,Adyen Payments - Credit Cards,rfETfyiWUaXtr6wbW1or3e12i,0.0,Patta,0.0,NaN,NaN,NaN,1.651530e+13,"DeliveryDefense risk level: Low, SupplierChina...",Low,web,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,North Carolina,North Carolina,rfETfyiWUaXtr6wbW1or3e12i,NaN,NaN,rfETfyiWUaXtr6wbW1or3e12i + aSF3q6fhQlGwkgGOOy...,2025,12,24
3,US4411,corey.lepore@gmail.com,paid,12/24/2025 1:39,fulfilled,1/4/2026 5:45,yes,USD,75.0,21.0,0.0,96.0,NaN,0.0,UPS Express,2025-12-23 21:38:00,1,Patta Oversized Tote Bag (Black),75.0,NaN,POC-AW25-3500-380-0001-001,True,True,fulfilled,Corey Lepore,2 Lyons Rd,2 Lyons Rd,NaN,NaN,Armonk,10504,NY,US,NaN,Corey Lepore,2 Lyons Road,2 Lyons Road,NaN,NaN,Armonk,10504,NY,US,9144190346,NaN,delivery_defense_score: 880,NaN,Adyen Payments - Credit Cards,rBsHHagYQ9qkJ9Ta5tB4FIkqY,0.0,Patta,0.0,NaN,NaN,NaN,1.651410e+13,"DeliveryDefense risk level: Low, SupplierChina...",Low,web,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,New York,New York,rBsHHagYQ9qkJ9Ta5tB4FIkqY,NaN,NaN,rBsHHagYQ9qkJ9Ta5tB4FIkqY + aCcnyMDun4rw99nuLy...,2025,12,23
4,US4410,hemicuda620@gmail.com,paid,12/23/2025 17:03,fulfilled,1/5/2026 14:45,yes,USD,152.0,16.8,0.0,168.8,NaN,0.0,UPS Express Saver,2025-12-23 13:01:00,1,Patta Embroidered Fire Panther Hooded Sweater ...,152.0,NaN,POC-AW25-2050-325-0026-001-L,True,True,fulfilled,Aspen Goodman,"576 Jaques Avenue, 2",576 Jaques Avenue,2,NaN,Rahway,7065,NJ,US,7324231758,Aspen Goodman,"576 Jaques Avenue, 2",576 Jaques Avenue,2,NaN,Rahway,7065,NJ,US,7324231758,NaN,delivery_defense_score: 866,NaN,Adyen Payments - Credit Cards,r7uOzcrG6pVrS9zGVejo25uNn,0.0,Patta,0.0,NaN,NaN,NaN,1.651350e+13,"DeliveryDefense risk level: Low, SupplierChina...",Low,web,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,New Jersey,New Jersey,r7uOzcrG6pVrS9zGVejo25uNn,NaN,NaN,r7uOzcrG6pVrS9zGVejo25uNn + at7dqUCKyuJDiSZK9a...,2025,12,23
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1744,US1007,hana.salem@hotmail.fr,paid,10/4/2023 11:56,unfulfilled,NaN,no,USD,45.0,0.0,0.0,45.0,NaN,0.0,NaN,2023-10-04 11:56:00,1,Patta Apple T-Shirt (Odyssey Gray) - M,45.0,NaN,POC-SS23-APPLE-TS-002-M,True,True,pending,Dont ship ME,1600 Amphitheatre Pkwy,1600 Amphitheatre Pkwy,NaN,Pattta,Mountain View,94043,CA,US,NaN,Dont ship ME,1600 Amphitheatre Pkwy,1600 Amphitheatre Pkwy,NaN,Pattta,Mountain View,94043,CA,US,NaN,NaN,NaN,NaN,manual,r8NVWFtC5aAgKKDDUC45iyaCh,0.0,Patta,0.0,Hana Salem,NaN,NaN,5.514810e+12,NaN,Low,shopify_draft_order,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,California,California,r8NVWFtC5aAgKKDDUC45iyaCh,NaN,NaN,r8NVWFtC5aAgKKDDUC45iyaCh,2023,10,4
1745,US1006,leander@patta.nl,paid,9/28/2023 9:47,fulfilled,9/28/2023 9:49,no,USD,45.0,0.0,0.0,45.0,NaN,0.0,NaN,2023-09-28 09:47:00,1,Patta Apple T-Shirt (Black) - XS,45.0,NaN,POC-SS23-APPLE-TS-001-XS,True,True,fulfilled,Christopher Guzman TEST,504 E 79th St apt 2c,504 E 79th St apt 2c,NaN,NaN,New York,10075,NY,US,NaN,Christopher Guzman TEST,"317 Dundas St W, Toronto, ON M5T 1G4, Canada","317 Dundas St W, Toronto, ON M5T 1G4, Canada",NaN,NaN,toronto,M5T 1G4,ON,CA,NaN,"2023-09-29 15:50 UTC\nReturnGO, RMA2156701:\nR...",NaN,NaN,manual,r0YurWeCgffOT8z8VPZn5rBRz,0.0,Patta,0.0,Hana Salem,NaN,NaN,5.508500e+12,Return requested via ReturnGO,Low,shopify_draft_order,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,New York,Ontario,r0YurWeCgffOT8z8VPZn5rBRz,NaN,NaN,r0YurWeCgffOT8z8VPZn5rBRz,2023,9,28
1746,US1005,tomas@patta.nl,paid,9/28/2023 9:43,fulfilled,9/28/2023 9:49,no,USD,45.0,0.0,7.5,45.0,NaN,0.0,NaN,2023-09-28 09:43:00,1,Patta Apple T-Shirt (Black) - S,45.0,NaN,POC-SS23-APPLE-TS-001-S,True,True,fulfilled,TEST ACCOUNT DONT SHIP,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,TEST ACCOUNT DONT SHIP TEST ACCOUNT DONT SHIP,"1600 Pennsylvania Avenue NW, Washington, DC 20...","1600 Pennsylvania Avenue NW, Washington, DC 20...",NaN,Patta,DC,20500,DC,US,NaN,"2023-09-29 15:02 UTC\nReturnGO, RMA2156433:\nR...",NaN,NaN,manual,rZrdQkDb5uw7p7ohMxUa79w6K,0.0,Patta,0.0,Hana Salem,Patta UK - Bleckmann Warehouse,NaN,5.508500e+12,Return requested via ReturnGO,Low,shopify_draft_order,0,GB VAT 20%,7.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Washington DC,rZrdQkDb5uw7p7ohMxUa79w6K,NaN,NaN,rZrdQkDb5uw7p7ohMxUa79w6K,2023,9,28
1747,US1003,leander@patta.nl,paid,8/21/2023 6:12,fulfilled,9/1/2023 10:43,no,USD,194.0,23.5,0.0,217.5,NaN,0.0,UPS Express,2023-08-21 06:12:00,1,Patta Apple T-Shirt (Odyssey Gray) - M,45.0,NaN,POC-SS23-APPLE-TS-002-M,True,True,fulfilled,Christopher Guzman TEST,504 E 79th St apt 2c,504 E 79th St apt 2c,NaN,NaN,New York,10075,NY,US,NaN,Christopher Guzman TEST,504 E 79th St apt 2c,504 E 79th St apt 2c,NaN,NaN,New York,10075,NY,US,NaN,NaN,NaN,NaN,manual,rC5TYcZQZGrmqlF0ywIiUOrsY,0.0,Patta,0.0,NaN,NaN,NaN,5.442750e+12,NaN,Low,shopify_draft_order,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,New York,New York,rC5TYcZQZGrmqlF0ywIiUOrsY,NaN,NaN,rC5TYcZQZGrmqlF0ywIiUOrsY,2023,8,21
1748,US1003,leander@patta.nl,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2023-08-21 06:12:00,1,Patta Argyle Knitted Cardigan (Light Brown Mel...,149.0,NaN,POC-SS23-ARGYLE-KC-001-L,True,True,fulfilled,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Patta,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2023,8,21